"""money_as_decimal

Revision ID: 31e82415610a
Revises: 6559d87f9f56
Create Date: 2026-04-22 11:18:21.199097

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31e82415610a'
down_revision: str | Sequence[str] | None = '6559d87f9f56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.alter_column('usd_to_eur_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=False)

    with op.batch_alter_table('historical_prices', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=28, scale=8),
               existing_nullable=True)
        batch_op.alter_column('price_per_share',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
        batch_op.alter_column('fee',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
        batch_op.alter_column('eur_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
        batch_op.alter_column('split_ratio',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True)
        batch_op.alter_column('fx_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('fx_rate',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('split_ratio',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('eur_amount',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('fee',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price_per_share',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=28, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('historical_prices', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.alter_column('usd_to_eur_rate',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
