"""baseline

Revision ID: 6559d87f9f56
Revises:
Create Date: 2026-04-22 11:10:54.786692

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6559d87f9f56'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usd_to_eur_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_date'), ['date'], unique=False)

    op.create_table('historical_prices',
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    with op.batch_alter_table('historical_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_prices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_prices_ticker'), ['ticker'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('oauthaccount',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('oauth_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('account_email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauthaccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauthaccount_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauthaccount_oauth_name'), ['oauth_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauthaccount_user_id'), ['user_id'], unique=False)

    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_user_id'), ['user_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'BUY', 'FEE', 'SELL', 'WITHDRAW', 'SPLIT', 'DIVIDEND', name='transactiontype'), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price_per_share', sa.Float(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('eur_amount', sa.Float(), nullable=True),
    sa.Column('split_ratio', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('fx_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('ix_transaction_portfolio_date', ['portfolio_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_portfolio_id'), ['portfolio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_portfolio_id'))
        batch_op.drop_index('ix_transaction_portfolio_date')

    op.drop_table('transaction')
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_name'))

    op.drop_table('portfolio')
    with op.batch_alter_table('oauthaccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauthaccount_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauthaccount_oauth_name'))
        batch_op.drop_index(batch_op.f('ix_oauthaccount_account_id'))

    op.drop_table('oauthaccount')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('historical_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_prices_ticker'))
        batch_op.drop_index(batch_op.f('ix_historical_prices_date'))

    op.drop_table('historical_prices')
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_date'))

    op.drop_table('fx_rates')
    # ### end Alembic commands ###

    # PostgreSQL creates a standalone enum type for sa.Enum(..., name='transactiontype');
    # it is NOT dropped with the transaction table and blocks re-running upgrade().
    # SQLite treats the enum as VARCHAR, so the drop is a no-op there.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="transactiontype").drop(bind, checkfirst=True)
