"""drop_redundant_pk_indexes

Revision ID: d23090e24a6b
Revises: 31e82415610a
Create Date: 2026-04-22 14:12:07.739397

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd23090e24a6b'
down_revision: str | Sequence[str] | None = '31e82415610a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent: uses if_exists=True so the migration is a no-op on databases
    created via the pre-Alembic create_db_and_tables() path with current
    models (where these redundant indexes were never emitted).
    """
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_date'), if_exists=True)

    with op.batch_alter_table('historical_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_prices_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_historical_prices_ticker'), if_exists=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_prices_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_prices_date'), ['date'], unique=False)

    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_date'), ['date'], unique=False)

    # ### end Alembic commands ###
