/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Basic health check endpoint
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/cookie/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Cookie.Login */
        post: operations["auth_cookie_login_auth_cookie_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/cookie/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Cookie.Logout */
        post: operations["auth_cookie_logout_auth_cookie_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Forgot Password */
        post: operations["reset_forgot_password_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth:Google.Oauth Cookie.Authorize */
        get: operations["oauth_google_oauth_cookie_authorize_auth_google_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oauth:Google.Oauth Cookie.Callback
         * @description The response varies based on the authentication backend used.
         */
        get: operations["oauth_google_oauth_cookie_callback_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-verify-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Request-Token */
        post: operations["verify_request_token_auth_request_verify_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Reset Password */
        post: operations["reset_reset_password_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Verify */
        post: operations["verify_verify_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check: DB liveness plus cache and migration freshness.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Portfolios
         * @description Get all portfolios
         */
        get: operations["list_portfolios_portfolios__get"];
        put?: never;
        /**
         * Create Portfolio
         * @description Create a new portfolio
         */
        post: operations["create_portfolio_portfolios__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/prices/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Live Prices
         * @description Get current prices and FX rate without replaying transactions.
         *
         *     Each ticker's ``source`` is ``live`` when Yahoo Finance returned a fresh
         *     price, ``last_known`` when the DB cache was used because the live fetch
         *     failed, or ``missing`` when neither is available. Clients render
         *     stale/missing badges and banners based on this.
         */
        get: operations["get_live_prices_portfolios_prices_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description Get a specific portfolio
         */
        get: operations["get_portfolio_portfolios__portfolio_id__get"];
        /**
         * Update Portfolio
         * @description Update a portfolio
         */
        put: operations["update_portfolio_portfolios__portfolio_id__put"];
        post?: never;
        /**
         * Delete Portfolio
         * @description Delete a portfolio and all its transactions
         */
        delete: operations["delete_portfolio_portfolios__portfolio_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy Portfolio
         * @description Copy a portfolio with all its transactions
         */
        post: operations["copy_portfolio_portfolios__portfolio_id__copy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio Performance
         * @description Get portfolio performance over time as a time series of portfolio values.
         */
        get: operations["get_portfolio_performance_portfolios__portfolio_id__performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio Status
         * @description Get portfolio status with holdings, cash balance, and performance metrics
         */
        get: operations["get_portfolio_status_portfolios__portfolio_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description Get paginated transactions for a specific portfolio
         */
        get: operations["list_transactions_portfolios__portfolio_id__transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Transaction
         * @description Create a new transaction for a portfolio
         */
        post: operations["create_transaction_portfolios__portfolio_id__transactions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/transactions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Transactions
         * @description Export all transactions for a portfolio as CSV
         */
        get: operations["export_transactions_portfolios__portfolio_id__transactions_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/transactions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Transactions Csv
         * @description Import a CSV file to bulk import transactions.
         *
         *     Expected CSV format:
         *     date,type,ticker,quantity,price_per_share,fee,total_amount,eur,split_ratio,currency,fx_rate
         *     2/12/2020 20:14:39,Deposit,,,,,3000,2760.27,,USD,1.0871
         *     2/12/2020 20:16:10,Buy,MSFT,15.00000001,183.69,0.00,"-2,755.35",,,,
         *
         *     Pass ``?dry_run=true`` to validate the CSV and preview counts without
         *     persisting; subsequent re-submission without the flag commits the data.
         */
        post: operations["import_transactions_csv_portfolios__portfolio_id__transactions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Transaction
         * @description Update a transaction
         */
        put: operations["update_transaction_transactions__transaction_id__put"];
        post?: never;
        /**
         * Delete Transaction
         * @description Delete a transaction
         */
        delete: operations["delete_transaction_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User Me */
        get: operations["get_current_user_me_users_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Current User
         * @description Permanently delete the current user and all associated data.
         */
        delete: operations["delete_current_user_users_me_delete"];
        options?: never;
        head?: never;
        /** Users:Patch Current User */
        patch: operations["users_patch_current_user_users_me_patch"];
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:User */
        get: operations["users_user_users__id__get"];
        put?: never;
        post?: never;
        /** Users:Delete User */
        delete: operations["users_delete_user_users__id__delete"];
        options?: never;
        head?: never;
        /** Users:Patch User */
        patch: operations["users_patch_user_users__id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_auth_cookie_login_auth_cookie_login_post */
        Body_auth_cookie_login_auth_cookie_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** Body_import_transactions_csv_portfolios__portfolio_id__transactions_import_post */
        Body_import_transactions_csv_portfolios__portfolio_id__transactions_import_post: {
            /** File */
            file: string;
        };
        /** Body_reset_forgot_password_auth_forgot_password_post */
        Body_reset_forgot_password_auth_forgot_password_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_reset_reset_password_auth_reset_password_post */
        Body_reset_reset_password_auth_reset_password_post: {
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /** Body_verify_request_token_auth_request_verify_token_post */
        Body_verify_request_token_auth_request_verify_token_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_verify_verify_auth_verify_post */
        Body_verify_verify_auth_verify_post: {
            /** Token */
            token: string;
        };
        /**
         * BulkImportResponse
         * @description Schema for CSV bulk import response.
         *
         *     When ``dry_run=True``, ``imported_count`` and ``skipped_count`` are
         *     projections of what *would* happen and ``transactions`` is empty —
         *     the un-persisted parsed rows have no DB ids, so we omit them rather
         *     than fake the response shape. The frontend uses these counts to show
         *     a confirmation dialog before re-submitting without ``dry_run``.
         */
        BulkImportResponse: {
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /** Imported Count */
            imported_count: number;
            /** Skipped Count */
            skipped_count: number;
            /** Transactions */
            transactions: components["schemas"]["TransactionResponse"][];
        };
        /** CloseAccountRequest */
        CloseAccountRequest: {
            /** Confirmation */
            confirmation?: string | null;
            /** Password */
            password?: string | null;
        };
        /**
         * DividendReceivedResponse
         * @description Schema for a single dividend payment record.
         */
        DividendReceivedResponse: {
            /** Amount */
            amount: number;
            /** Amount Eur */
            amount_eur?: number | null;
            /** Date */
            date: string;
            /** Ticker */
            ticker: string;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health-check response: DB liveness plus cache and migration freshness.
         */
        HealthResponse: {
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "error";
            /** Last Fx Rate Age */
            last_fx_rate_age?: number | null;
            /** Migrations Head */
            migrations_head?: string | null;
            /** Price Cache Age */
            price_cache_age?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "unhealthy";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Version */
            version: string;
        };
        /**
         * HoldingResponse
         * @description Schema for a single holding (transaction-derived only)
         */
        HoldingResponse: {
            /** Average Cost */
            average_cost: number;
            /**
             * First Buy Date
             * Format: date
             */
            first_buy_date: string;
            /** Quantity */
            quantity: number;
            /** Ticker */
            ticker: string;
            /** Total Cost */
            total_cost: number;
        };
        /**
         * LivePriceInfo
         * @description Per-ticker live-price result with provenance.
         *
         *     ``source`` distinguishes a fresh Yahoo Finance fetch (``live``) from a
         *     stale fallback pulled from the HistoricalPrice cache (``last_known``) and
         *     from the "no data at all" case (``missing``). ``as_of`` is the timestamp
         *     of the price — now for live, the cached date for last_known, None for missing.
         *
         *     Invariants:
         *       * ``price is None`` iff ``source == 'missing'``.
         *       * ``as_of is None`` iff ``source == 'missing'``. A priced result always
         *         carries a timestamp; "missing" carries neither.
         */
        LivePriceInfo: {
            /** As Of */
            as_of?: string | null;
            /** Price */
            price?: number | null;
            /**
             * Source
             * @default missing
             * @enum {string}
             */
            source: "live" | "last_known" | "missing";
        };
        /**
         * LivePricesResponse
         * @description Schema for live price polling (no transaction replay)
         */
        LivePricesResponse: {
            /** Prices */
            prices: {
                [key: string]: components["schemas"]["LivePriceInfo"];
            };
            /**
             * Provider Unavailable
             * @default false
             */
            provider_unavailable: boolean;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Usd To Eur Rate */
            usd_to_eur_rate?: number | null;
        };
        /** OAuth2AuthorizeResponse */
        OAuth2AuthorizeResponse: {
            /** Authorization Url */
            authorization_url: string;
        };
        /**
         * PaginatedTransactionResponse
         * @description Schema for paginated transaction response
         */
        PaginatedTransactionResponse: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
            /** Transactions */
            transactions: components["schemas"]["TransactionResponse"][];
        };
        /**
         * PerformanceDataPoint
         * @description Schema for a single performance data point
         */
        PerformanceDataPoint: {
            /** Current Value */
            current_value?: number | null;
            /** Date */
            date: string;
            /** Fx Rate */
            fx_rate?: number | null;
            /**
             * Principal
             * @default 0
             */
            principal: number;
            /** Principal Eur */
            principal_eur?: number | null;
            /** Return Pct */
            return_pct?: number | null;
            /** Sp500 Return Pct */
            sp500_return_pct?: number | null;
        };
        /**
         * PortfolioBase
         * @description Base portfolio schema (used for both create and update).
         */
        PortfolioBase: {
            /** Name */
            name: string;
        };
        /**
         * PortfolioCopy
         * @description Schema for copying a portfolio
         */
        PortfolioCopy: {
            /** New Name */
            new_name: string;
        };
        /**
         * PortfolioPerformanceResponse
         * @description Schema for portfolio performance over time
         */
        PortfolioPerformanceResponse: {
            /** Cost Basis Fallback Tickers */
            cost_basis_fallback_tickers?: string[];
            /** Data Points */
            data_points: components["schemas"]["PerformanceDataPoint"][];
            /** Portfolio Id */
            portfolio_id: number;
            /** Portfolio Name */
            portfolio_name: string;
            /** Warnings */
            warnings?: components["schemas"]["TransactionWarning"][];
        };
        /**
         * PortfolioResponse
         * @description Schema for portfolio response
         */
        PortfolioResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * PortfolioStatusResponse
         * @description Schema for portfolio status (transaction-derived metrics only).
         *
         *     EUR aggregates are nullable: when any contributing transaction lacks a
         *     usable historical FX rate (and no explicit ``eur_amount``/``fx_rate``),
         *     the corresponding aggregate is reported as ``None`` instead of being
         *     silently distorted by today's rate. ``eur_incomplete`` is the ergonomic
         *     OR-of-the-three for the UI; ``fx_missing_tx_ids`` lists the offending
         *     transactions so the UI can deep-link the user to the fix.
         */
        PortfolioStatusResponse: {
            /** Capital Gains Tax Rate */
            capital_gains_tax_rate: number;
            /** Cash */
            cash: number;
            /** Dividends */
            dividends: number;
            /** Dividends Eur */
            dividends_eur?: number | null;
            /** Dividends Received */
            dividends_received?: components["schemas"]["DividendReceivedResponse"][];
            /**
             * Eur Incomplete
             * @default false
             */
            eur_incomplete: boolean;
            /** Fx Missing Tx Ids */
            fx_missing_tx_ids?: number[];
            /** Holdings */
            holdings: components["schemas"]["HoldingResponse"][];
            /** Holdings Cost */
            holdings_cost: number;
            /** Portfolio Id */
            portfolio_id: number;
            /** Portfolio Name */
            portfolio_name: string;
            /** Principal */
            principal: number;
            /** Principal Eur */
            principal_eur?: number | null;
            /** Principal Eur Avg */
            principal_eur_avg?: number | null;
            /** Realized Gains */
            realized_gains: number;
            /** Realized Sales */
            realized_sales?: components["schemas"]["RealizedSaleResponse"][];
            /** Realized Withdrawals */
            realized_withdrawals?: components["schemas"]["WithdrawalFxResponse"][];
            /**
             * Transaction Count
             * @default 0
             */
            transaction_count: number;
            /** Usd To Eur Rate */
            usd_to_eur_rate?: number | null;
            /** Warnings */
            warnings?: components["schemas"]["TransactionWarning"][];
        };
        /**
         * RealizedSaleResponse
         * @description Schema for a single realized sale record.
         */
        RealizedSaleResponse: {
            /** Cost Basis */
            cost_basis: number;
            /** Date */
            date: string;
            /** First Buy Date */
            first_buy_date: string;
            /** Proceeds */
            proceeds: number;
            /** Quantity */
            quantity: number;
            /** Quantity Before */
            quantity_before: number;
            /** Realized Gain */
            realized_gain: number;
            /** Ticker */
            ticker: string;
        };
        /**
         * TransactionCreate
         * @description Schema for creating a transaction
         */
        TransactionCreate: {
            /** Currency */
            currency?: string | null;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Eur Amount */
            eur_amount?: number | null;
            /** Fee */
            fee?: number | null;
            /** Fx Rate */
            fx_rate?: number | null;
            /** Price Per Share */
            price_per_share?: number | null;
            /** Quantity */
            quantity?: number | null;
            /** Split Ratio */
            split_ratio?: number | null;
            /** Ticker */
            ticker?: string | null;
            /** Total Amount */
            total_amount: number;
            type: components["schemas"]["TransactionType"];
        };
        /**
         * TransactionResponse
         * @description Schema for transaction response
         */
        TransactionResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency?: string | null;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Eur Amount */
            eur_amount?: number | null;
            /** Fee */
            fee?: number | null;
            /** Fx Rate */
            fx_rate?: number | null;
            /** Id */
            id: number;
            /** Portfolio Id */
            portfolio_id: number;
            /** Price Per Share */
            price_per_share?: number | null;
            /** Quantity */
            quantity?: number | null;
            /** Split Ratio */
            split_ratio?: number | null;
            /** Ticker */
            ticker?: string | null;
            /** Total Amount */
            total_amount: number;
            type: components["schemas"]["TransactionType"];
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * TransactionType
         * @description Transaction type enumeration
         * @enum {string}
         */
        TransactionType: "Deposit" | "Buy" | "Fee" | "Sell" | "Withdraw" | "Split" | "Dividend";
        /**
         * TransactionUpdate
         * @description Schema for updating a transaction (all fields optional)
         */
        TransactionUpdate: {
            /** Currency */
            currency?: string | null;
            /** Date */
            date?: string | null;
            /** Eur Amount */
            eur_amount?: number | null;
            /** Fee */
            fee?: number | null;
            /** Fx Rate */
            fx_rate?: number | null;
            /** Price Per Share */
            price_per_share?: number | null;
            /** Quantity */
            quantity?: number | null;
            /** Split Ratio */
            split_ratio?: number | null;
            /** Ticker */
            ticker?: string | null;
            /** Total Amount */
            total_amount?: number | null;
            type?: components["schemas"]["TransactionType"] | null;
        };
        /**
         * TransactionWarning
         * @description Structured warning from transaction processing, for frontend i18n.
         */
        TransactionWarning: {
            /** Code */
            code: string;
            /** Date */
            date: string;
            /** Params */
            params?: {
                [key: string]: string;
            };
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean | null;
            /** Name */
            name?: string | null;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /** Name */
            name?: string | null;
            /** Oauth Providers */
            oauth_providers?: string[];
            /** Picture */
            picture?: string | null;
            /**
             * Tax Rate
             * @default 0.255
             */
            tax_rate: number;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Superuser */
            is_superuser?: boolean | null;
            /** Is Verified */
            is_verified?: boolean | null;
            /** Name */
            name?: string | null;
            /** Password */
            password?: string | null;
            /** Picture */
            picture?: string | null;
            /** Tax Rate */
            tax_rate?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WithdrawalFxResponse
         * @description Schema for a single withdrawal with realized FX gain/loss.
         *
         *     EUR fields are nullable: when the historical FX rate for the withdrawal
         *     date — or the running EUR principal — is unavailable, the EUR figures are
         *     reported as ``None`` rather than silently filled with today's live rate.
         */
        WithdrawalFxResponse: {
            /** Amount */
            amount: number;
            /** Amount Eur */
            amount_eur?: number | null;
            /** Amount Eur Avg */
            amount_eur_avg?: number | null;
            /** Date */
            date: string;
            /** Realized Fx Gain */
            realized_fx_gain?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_cookie_login_auth_cookie_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_cookie_login_auth_cookie_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_cookie_logout_auth_cookie_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reset_forgot_password_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_forgot_password_auth_forgot_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_oauth_cookie_authorize_auth_google_authorize_get: {
        parameters: {
            query?: {
                scopes?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuth2AuthorizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_oauth_cookie_callback_auth_google_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                code_verifier?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_request_token_auth_request_verify_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_request_token_auth_request_verify_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_reset_password_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_reset_password_auth_reset_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_verify_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_verify_auth_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_portfolios_portfolios__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"][];
                };
            };
        };
    };
    create_portfolio_portfolios__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioBase"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_prices_portfolios_prices_live_get: {
        parameters: {
            query?: {
                tickers?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivePricesResponse"];
                };
            };
            /** @description Too many tickers requested */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_portfolio_portfolios__portfolio_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioBase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_portfolios__portfolio_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_portfolio_portfolios__portfolio_id__copy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCopy"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_performance_portfolios__portfolio_id__performance_get: {
        parameters: {
            query?: {
                /** @description Start date in YYYY-MM-DD format */
                start_date?: string | null;
                /** @description End date in YYYY-MM-DD format */
                end_date?: string | null;
                /** @description Number of data points to return */
                num_points?: number;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioPerformanceResponse"];
                };
            };
            /** @description Invalid date format or date range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_status_portfolios__portfolio_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioStatusResponse"];
                };
            };
            /** @description Invalid portfolio data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_portfolios__portfolio_id__transactions_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
                /** @description Filter by ticker (partial, case-insensitive) */
                ticker?: string | null;
                /** @description Filter by transaction type(s) */
                type?: string[] | null;
                /** @description Sort by date: asc or desc */
                sort_order?: string;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_portfolios__portfolio_id__transactions__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_transactions_portfolios__portfolio_id__transactions_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_transactions_csv_portfolios__portfolio_id__transactions_import_post: {
        parameters: {
            query?: {
                /** @description When true, parse + dedup but do not write. Returns projected imported/skipped counts so the UI can confirm before committing. */
                dry_run?: boolean;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_transactions_csv_portfolios__portfolio_id__transactions_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_transactions__transaction_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    delete_current_user_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Incorrect password or missing DELETE confirmation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_patch_current_user_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_user_users__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_delete_user_users__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_patch_user_users__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
